.TH "" "1" "October 2024" "git-open 2.2.4" "Git manual"
.SH "NAME"
\fB\fR
.TS
tab(|) nowarn;
cx.
T{
.P
@xkeshav/gh\-repo\-care \- The community health files generator for your github repo to make it open source friendly

T}
.TE
.SH SYNOPSIS
.P
\fBnpx gh\-repo\-care [\-\-version]  [\-V] \fP
.SH DESCRIPTION
.P
A community health file generator, it will ask few questions and then generate files in \.github folder
.SH EXAMPLES
.SH LICENSE
.P
MIT

