name: Auto assign Issue

on:
  issues:
    types: [opened, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Check if it's been requested
        id: check-if-requested
        run: |
          ISSUE_BODY=$(jq -r .issue.body "$GITHUB_EVENT_PATH")
          echo "Issue Body: $ISSUE_BODY"
          if echo "$ISSUE_BODY" | grep -q "I'd like to work on this Issue myself"; then
            echo "selfAssigned=true" >> $GITHUB_ENV
          else
            echo "selfAssigned=false" >> $GITHUB_ENV
          fi

      - name: Assign to issuer
        if: env.selfAssigned == 'true'
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.event.issue.user.login}}

      - name: Post a comment
        if: env.selfAssigned == 'true'
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          body: |
            🤖 meep morp!

            Thank you for your contribution ${{github.event.issue.user.login}}!! This Issue has been assigned to you as requested ✨

            🔎 Please keep in mind that in order to give everyone a chance to contribute Issues may be unassigned if they go stale.
            You will be warned if the Issue is marked as stale at any point.

            🔎 Please review our documentation for guidance on:
            - common Patterns we follow in the code base
            - conventions set for commit messages and naming functions, classes or files

            💡 The core team is available for any help and will try to respond to any comments in this Issue or questions on discord as quickly as possible.

            Happy coding ! 🦆
