name: markdown-lint
run-name: Linting Markdown files
env:
  DOCS_CHANGED: false
on:
  push:
    branches:
      - main
      - develop
jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check changed files
        id: check_file_changed
        run: |
          echo "### File Check! :rocket:" >> $GITHUB_STEP_SUMMARY
          # Get a list of changed files between the last commit and the previous commit
          changed_files=$(git diff --name-only HEAD^ HEAD)

          # Check if any of the changed files have a .md extension
          echo "Changed files: $changed_files"
          if echo "$changed_files" | grep -q '\.md$'; then
            echo "DOCS_CHANGED=true" >> $GITHUB_ENV
          else
            echo "DOCS_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Lint Markdown files
        if: ${{env.DOCS_CHANGED == true}}
        uses: ./.github/actions/md-lint
