name: Publish Package to NPM registry

on:
  release:
    types: [created, edited, prereleased]

jobs:
  publish-to-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/
          scope: "@xkeshav"
          provenance: true
      - run: npm ci
      - run: npm publish --provenance --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
